name:                jsondiff
version:             0.2.0.0
github:              "eunikolsky/jsondiff"
license:             BSD3
author:              "Eugene Nikolsky"
maintainer:          "e@egeek.me"
copyright:           "2022 Eugene Nikolsky"

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eunikolsky/jsondiff#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- mtl
- optparse-applicative
- text

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - aeson-pretty
  - vector

executables:
  jsondiff:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    # - -Wmissing-import-lists
    # - -Wmissing-export-lists
    - -Wcompat
    - -Widentities
    - -Wredundant-constraints
    - -fhide-source-paths
    - -Wpartial-fields
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jsondiff

tests:
  jsondiff-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jsondiff
    - hspec
    - raw-strings-qq
